### ISSUE TITLE
Option to not uwufy player chat channels (FC, party, shout, etc)

### ISSUE THREAD

**Issue by knelse** [goatcorp/DalamudPlugins#352]
Hello,
Not sure who's maintaining owofy, sorry in advance if the issue isn't for this repository.
What about a config option to exclude player interaction chats from owofy? Or even better, make chat selection somehow configurable.

I'd send a pull request, but I don't have access to source code and sending in dnspy-edited dll feels a bit wrong 😺

**Comment by goaaats** [comment]
Hey! Thanks for leaving a comment, this isn't the right place for it but it is acknowledged. The code for owo is at https://github.com/goaaats/dalamud-owo - if you wanna PR, feel free!

Cheers
