### ISSUE TITLE
Add repo URLs to the list of plugins Page

### ISSUE THREAD

**Issue by crw** [goatcorp/DalamudPlugins#554]
Adding a link to the plugin repo would be a significant quality of life improvement for new users of this product.

https://goatcorp.github.io/DalamudPlugins/plugins

repoUrl is included in the JSON package manifest, and this page seems to be auto-generated from the list of manifests.

The issue is the descriptions are generally not very informative, whereas the repos mostly have good readme files on what these things actually do.

**Comment by NotAdam** [comment]
what lol? its already shown ingame

**Comment by goaaats** [comment]
Yeah, most plugins include it now - you have to click the globe icon next to the install button. Does this do what you want it to do?

**Comment by crw** [comment]
For the most part, when I am in-game I am... playing the game. Some of the plugins are obviously useful but many are pretty unclear from the descriptions as to what they do and how they work. I spent some hours last night just playing around with plugins, but to be honest I have a limited patience for the "trial-and-error" approach to plugin discovery. I also don't load FFXIV so I can then spend a bunch of time reading web pages. 

Making it easier to research when I am not playing the game (for example, before I've even installed the launcher) would be a big benefit, I think, for those of us who do their research before installing. Right now I am basically searching google for the plugin repos or loading their repo links from the manifests to figure out what they do.

**Comment by reiichi001** [comment]
Can I interest you in helping maintain https://github.com/goatcorp/DalamudPlugins/wiki/Plugin-Gallery ? This is an old list, so it needs some pruning and for new things to be added. Ideally, we'd make all the devs do it, but they might also document elsewhere too

**Comment by crw** [comment]
Oh! Is that the source for that Github Pages link above? I thought it may be javascript that was parsing the list of manifests. TBH, the wiki page makes more sense. My first instinct was to look for a page to edit, so yes happy to help!

**Comment by reiichi001** [comment]
That one is manually maintained. It was originally copied off one that is generated though.
