### ISSUE TITLE
Crash to desktop related to ChatCoordinates when using GatherBuddy

### ISSUE THREAD

**Issue by AKA-Syenite** [goatcorp/DalamudPlugins#591]
> Only reproducible with Elm Logs (including partial match). Haven't encountered the issue with any other item.

> Does NOT occur if coordinates option is disabled, teleport and gear swap options have no effect that I've noticed. Crash occurs regardless of what zone character is currently in.

> Only tested on one character: https://na.finalfantasyxiv.com/lodestone/character/10049984

GatherBuddy issue: https://github.com/Ottermandias/GatherBuddy/issues/2

**Comment by AKA-Syenite** [comment]
@kissorjeyabalan I'm not certain whether this is an issue originating from GatherBuddy, or from ChatCoordinate

**Comment by reiichi001** [comment]
Hello,

Plugin issues should be reported to their respective repos' issues tracker or on the XIVLauncher discord, not on this repo, as this is just the storage means for plugins and individual plugin developers do not look here.

As FFXIV patch 5.5 brought large changes to both Dalamud and all plugins needed to be updated, we'll be closing this issue. If it's still happening after both of those plugins are updated I would recommend reaching out to their developers. Both of these plugins should have a repo link on their plugin entries in the installer, or can be reached in the XIVLauncher Discord as well.
