### ISSUE TITLE
TitleEdit breaks the aesthetician

### ISSUE THREAD

**Issue by AKA-Syenite** [goatcorp/DalamudPlugins#603]
If TitleEdit is enabled, when you switch environments in the aesthetician/fantasia UI the character model and background cease to render until the game is restarted. If the environment is switched multiple times, all game sound ceases to play. Plugin sounds (at least from sonar) are unaffected.

I believe @lmcintyre is the current maintainer of the active fork (can't open an issue over at https://github.com/lmcintyre/TitleEditPlugin)

**Comment by reiichi001** [comment]
Hello, 

That is the current maintainer. You may have more luck reporting this in the Discord directly, as issues should be made for the plugin in question and not for the plugin respository.

TitleEdit 2.2.2.0 should also resolve this.

**Comment by AmenneHolelane** [comment]
this issue should probably be closed as it is not relevant

**Comment by reiichi001** [comment]
Will be closing this issue.

Bug reports can/should be made on the XIVLauncher discord or on the main repo for the plugin, https://github.com/attickdoor/TitleEditPlugin/issues .
