### ISSUE TITLE
Globetrotter web page button ingame - dead link

### ISSUE THREAD

**Issue by Kherae** [goatcorp/DalamudPlugins#604]
the webpage button for the Globetrotter addon, ingame from xlplugins config, links to `https://sr.ht/~jkcclemens/Globetrotter/`, which gives a 404

**Comment by reiichi001** [comment]
Hello,

I've contacted the plugin maintainer about this. It's generally best to reach them on Discord as plugin issues should be reported to the maintainer directly and not here.

**Comment by ascclemens** [comment]
This is fixed.
