### ISSUE TITLE
Gatherbuddy: Outdated collectable coordinates.

### ISSUE THREAD

**Issue by Kherae** [goatcorp/DalamudPlugins#618]
recently, several collectables were moved, including lover's laurel. addon hasn't been updated to account and still points at the old locations.

**Comment by reiichi001** [comment]
Hello, 

Please report issues to the plugin maintainer. Not to this repository.

You can find their repo by clicking on the global icon in /xlplugins, https://github.com/Ottermandias/GatherBuddy, or by contacting them on discord.

**Comment by Kherae** [comment]
moved. whoops, sorry.
