### ISSUE TITLE
XIVCombo not updating Spread Shot icon with Autocrossbow.

### ISSUE THREAD

**Issue by SillyEcho** [goatcorp/DalamudPlugins#695]
When Hypercharged as MCH, Spread Shot icon doesn't change to Autocrossbow during Hypercharge duration.

However, Autocrossbow is still used when using Spread Shot when Hypercharged, so it is mostly a cosmetic problem that is low priority.

**Comment by reiichi001** [comment]
Plugin issues should be reported to the plugin repo's issues location directly.

XIVCombo's can be found here: https://github.com/attickdoor/XIVComboPlugin/issues

Otherwise, you can also report this issue on our discord's #plugin_issues_help channel.
