### ISSUE TITLE
Crash Market board

### ISSUE THREAD

**Issue by Luna664** [goatcorp/DalamudPlugins#781]
Hello, I would like to report a crash of the plugin when searching for the "Combed Wool Rug" item

**Comment by reiichi001** [comment]
This is not the appropriate place to report a plugin issue. Please report this on the XIVLauncher Discord's #plugin_issues_help channel or if it's a consistent crash that's reproducible, on the specific plugin's github's issue tracker.

It appears to be working fine though. Perhaps you encountered a network issue?
![image](https://user-images.githubusercontent.com/10376708/116112455-6bc9d400-a66c-11eb-8d55-7546719b0273.png)

**Comment by Luna664** [comment]
Okay I'll post this on discord, because when I search for this item it crashes every time

![image](https://user-images.githubusercontent.com/75101727/116174199-3d9cd080-a70e-11eb-90c3-f8a2438fa18f.png)
