### ISSUE TITLE
Sound Filter git doesn't exist

### ISSUE THREAD

**Issue by GuyInDogSuit** [goatcorp/DalamudPlugins#921]
I would like some assistance with using this plugin but the link from both this page and the one linked to from Dalamud's interface do not work, nor does the repository even exist. I can't find instructions or a guide on how to use this. The log is just a mess, and I don't know how to properly filter it to find the specific bgms I'm trying to filter ("Four-Sided Circle" and "A Reason to Live" being two of them). This might not be the place to ask, but I don't know where to look as googling brings up almost nothing.

**Comment by goofy-somebody** [comment]
Asking in the Discord is usually a good start
https://discord.gg/3NMcUV5

SoundFilter, at least for me, tends to be on the very technical side of plugins, so try the Discord first

There is also a preset-sharing channel that may have what you are looking for if someone has found those filters

**Comment by reiichi001** [comment]
The SoundFilter repo is https://git.sr.ht/~jkcclemens/SoundFilter , but plugin support is mostly on Discord unless the develop provides another space for support on their own.
